In [1]:
import random
import numpy as np

In [55]:
def gerar_individuo(qte_genes):
    return np.random.randint(0,2, size=[qte_genes])

In [61]:
def gerar_populacao(tam_pop, qte_genes):
    return np.array([gerar_individuo(qte_genes) for _ in range(tam_pop)])

In [62]:
def fitness(ind):
    return np.sum(ind)

In [117]:
pop = gerar_populacao(10,10)

In [118]:
def selecionar_pais(pop, tam_pop, k=3):
    '''
    TORNEIO
    '''
    pais = []
    for torneio in range(tam_pop):
        idx = np.random.randint(0, tam_pop, size=k)
        g_idx = np.argmax(np.apply_along_axis(np.sum, axis=1, arr=pop[idx]))
        pais.append(pop[idx][g_idx])
        
    return np.array(pais)

In [119]:
print(pop)

[[0 1 0 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [0 0 1 0 0 1 0 0 0 0]
 [1 0 1 0 0 1 0 1 0 1]
 [0 0 0 1 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 1 0 1]
 [1 0 1 1 1 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0]
 [0 0 0 1 0 0 1 1 0 0]
 [0 1 1 1 1 0 0 1 1 1]]


In [120]:
pais = selecionar_pais(pop, tam_pop=10, k=3)

In [135]:
def gerar_filhos(pais, tam_pop, taxa_crossover=0.7):
    nova_pop = []
    
    for i in range(tam_pop//2):
        pai1 = random.choice(pais)
        pai2 = random.choice(pais)
        
        if random.random() < taxa_crossover:
            corte = random.randint(1, len(pai1)-1)
            filho1 = np.concatenate((pai1[:corte],pai2[corte:]))
            filho2 = np.concatenate((pai2[:corte], pai1[corte:]))
            nova_pop.append(filho1)
            nova_pop.append(filho2)
            
        else:
            nova_pop.append(pai1)
            nova_pop.append(pai2)
            
    return nova_pop

In [137]:
def mutacao(pop, tam_pop, qte_genes, taxa_mutacao=0.005):
    nova_pop = []
    for i in range(tam_pop):
        individuo = []
        for j in range(qte_genes):
            if random.random() < taxa_mutacao:
                if pop[i][j] == 0:
                    individuo.append(1)
                else:
                    individuo.append(0)
            else:
                individuo.append(pop[i][j])
            
        nova_pop.append(np.array(individuo))
        
    return np.array(nova_pop)

In [141]:
tam_pop = 10
qte_genes=50
taxa_crossover = 0.7
pop = gerar_populacao(tam_pop, qte_genes)
for i in range(1000):
    pais = selecionar_pais(pop, tam_pop)
    pop = gerar_filhos(pais, tam_pop)
    pop = mutacao(pop, tam_pop, qte_genes)

In [142]:
pop

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1